version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: dev-unode-ytuner_server_1
      APP_PORT: 8090

  server:
    image: servietos/ytuner-umbrel:1.2.6
    container_name: dev-unode-ytuner-server
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data:/data
