version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: invidious_web_1
      APP_PORT: 3000

  web:
    image: quay.io/invidious/invidious:latest
    restart: on-failure
    stop_grace_period: 1m
    user: "1000:1000"
    # Using official images that include tini
    #init: true
    environment:
      INVIDIOUS_CONFIG: |
        db:
          dbname: invidious
          user: umbrel
          password: 123
          host: unode-invidious_postgres_1
          port: 5432
        check_tables: true
        external_port: 3420
        captcha_enabled: false
        admins: ["umbrel"]
        default_user_preferences:
          feed_menu: ["Trending", "Subscriptions", "Playlists"]
          default_home: Trending
        hmac_key: "${APP_SEED}"
    healthcheck:
      disable: true
    depends_on:
      - postgres

  postgres:
    image: docker.io/library/postgres:14
    restart: on-failure
    user: "1000:1000"
    stop_grace_period: 1m
    init: true
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: invidious
      POSTGRES_USER: umbrel
      POSTGRES_PASSWORD: 123
