version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: unode-chromium_server_1
      APP_PORT: 3000

  server:
    image: ghcr.io/linuxserver/chromium:latest
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    shm_size: "1gb"
