version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  server:
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    environment:
      - VIRTUAL_HOST=${APP_DOMAIN}
      - WEBPASSWORD=${APP_PASSWORD}
      - WEB_PORT=8082
      # Listen on all interfaces, permit all origins
      - DNSMASQ_LISTENING=all
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
