version: "3.9.1"

services:
  server:
    image: pihole/pihole:2025.02.6
    # Pi-hole doesn't currently support running as non-root
    # https://github.com/pi-hole/docker-pi-hole/issues/685
    # user: "1000:1000"
    restart: on-failure
    network_mode: host
    volumes:
      - ${APP_DATA_DIR}/data/pihole:/etc/pihole/
      - ${APP_DATA_DIR}/data/dnsmasq:/etc/dnsmasq.d/
    environment:
      - VIRTUAL_HOST=${APP_DOMAIN}
      - WEBPASSWORD=${APP_PASSWORD}
      - APP_PORT=80
      # Listen on all interfaces, permit all origins
      - DNSMASQ_LISTENING=all
    cap_add:
      - NET_ADMIN
